[package]
name = "submodel"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
common_failures = { path = "../common_failures" }
csv = "0.15"
failure = "0.1"
flate2 = "1.0"
regex = "0.2"
tar = "0.4"
unicode-casefold = "0.2"
unicode-segmentation = "1.1"
